### ISSUE TITLE
Extension does not work with Inkscape 1.0beta2 on macOS 

### ISSUE THREAD

**Issue by virtualritz** [missinglinkelectronics/sphinxcontrib-svg2pdfconverter#5] opened 2020-01-25 02:24 UTC
```
> inkscape --version
Inkscape 1.0beta2 (ab38949, 2019-12-24)
    Pango version: 1.43.0
```

```
> make latexpdf
Running Sphinx v2.3.1
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: [new config] 7 added, 0 changed, 0 removed
reading sources... [100%] script_objects
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing nsi.tex... index background interface nodes script_objects guidelines acknowledgments
resolving references...
    Pango version: 1.43.0
Unknown option --export-pdf=/Users/moritz/code/nsi-docs/docs/_build/doctrees/images/nsi_logo.pdf
failed

Extension error:
Inkscape exited with error:
[stderr]
None
[stdout]
b''
make: *** [latexpdf] Error 1
```

**Comment by sephalon** [comment] 2020-04-16 12:51
Inkscape 1.0 comes with breaking changes in its CLI. Please have a look at branch `inkscape-v1.0`, which distinguishes between the Inkscape pre and post 1.0 CLI. Since I do not have the possibility to test on macOS, I would be interested in your feedback.

However I will not merge this until Inkscape 1.0 is finally out, since the CLI seems not to have stabilized yet: From 1.0beta2 to 1.0rc1 the corresponding long option changed from `--export-file` to `--export-filename` once again.

**Comment by davbeek** [comment] 2020-05-09 16:02
I am using Inkscape 1.0 for Mac from 1 May 2020. I can confirm the option is still --export-filename. From inkscape --help:
```
File export:                        
  -o, --export-filename=EXPORT-FILENAME
```
If there is anything I can do to test/help, please let me know.

**Comment by sephalon** [comment] 2020-05-26 11:36
@davbeek Thank you! Merged into master.

**Closed by sephalon** 2020-05-26 11:36 UTC
